# Generated by Django 4.1.7 on 2023-05-27 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='sharedUsers',
            field=models.ManyToManyField(
                related_name='sharedUsers',
                to=settings.AUTH_USER_MODEL),
        ),
    ]
