# Generated by Django 4.1.7 on 2023-06-07 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_sharedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='font',
            field=models.CharField(default='Helvetica', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='fontSize',
            field=models.IntegerField(default=12),
        ),
    ]
