# Generated by Django 4.1.7 on 2023-06-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_font_note_fontsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='fontSize',
            field=models.IntegerField(default=16),
        ),
    ]
