# Generated by Django 4.1.7 on 2023-07-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_fontsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='backgroundImage',
            field=models.CharField(default='wavy', max_length=100),
        ),
    ]
