# Generated by Django 4.1.7 on 2023-07-06 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_folder_backgroundimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='backgroundImage',
        ),
    ]
