# Generated by Django 4.1.7 on 2023-07-15 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_preferances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='folder',
        ),
        migrations.AddField(
            model_name='folder',
            name='home',
            field=models.BooleanField(
                default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to='notes.folder'),
        ),
        migrations.AlterField(
            model_name='note',
            name='folder',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to='notes.folder'),
        ),
    ]
