# Generated by Django 4.1.7 on 2023-08-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_alter_folder_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='fontSize',
            field=models.IntegerField(default=18),
        ),
    ]
