# Generated by Django 4.1.7 on 2024-12-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_remove_note_font_remove_note_fontsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='displayText',
            field=models.TextField(default='', max_length=7000),
        ),
        migrations.AlterField(
            model_name='preferances',
            name='backgroundImage',
            field=models.CharField(default='retro', max_length=100),
        ),
    ]
