# Generated by Django 4.0.4 on 2022-08-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginbasic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lastAccessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
