# Generated by Django 4.0.4 on 2023-02-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginbasic', '0002_alter_note_lastaccessed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='Unammed', max_length=100),
        ),
    ]
