# Generated by Django 4.0.4 on 2023-02-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginbasic', '0003_folder_alter_note_text_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
