# Generated by Django 4.1.7 on 2023-03-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginbasic', '0004_alter_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='folder',
            field=models.IntegerField(default=0),
        ),
    ]
