# Generated by Django 4.1.7 on 2023-03-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginbasic', '0005_note_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder',
            field=models.IntegerField(default=0),
        ),
    ]
