# Generated by Django 4.1.7 on 2023-03-13 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginbasic', '0006_folder_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
