# Generated by Django 4.1.7 on 2023-05-17 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginbasic', '0009_note_sharedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='sharedUsers',
            field=models.ManyToManyField(blank=True, related_name='sharedUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
